name: Metrics

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate topics-only metrics (icons, unlimited)
        uses: lowlighter/metrics@latest
        with:
          user: ${{ github.repository_owner }}
          filename: metrics.topics.svg
          base: ""

          plugin_topics: yes
          plugin_topics_mode: icons
          plugin_topics_limit: 0
          plugin_topics_sort: stars
